export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",
  AUTH_REFRESH_REUSE: "AUTH_REFRESH_REUSE",
  AUTH_REFRESH_EXPIRED: "AUTH_REFRESH_EXPIRED",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_NOT_AUTHENTICATED: "AUTH_NOT_AUTHENTICATED",
  AUTH_NO_TOKEN: "AUTH_NO_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_NO_REFRESH_TOKEN: "AUTH_NO_REFRESH_TOKEN",
  AUTH_COOKIE_PARSER_MISSING: "AUTH_COOKIE_PARSER_MISSING",

  // Authorization / role
  FORBIDDEN: "FORBIDDEN",
  RESERVATION_CUSTOMER_ONLY: "RESERVATION_CUSTOMER_ONLY",
  RESERVATION_NOT_OWNER: "RESERVATION_NOT_OWNER",
  RESERVATION_OWNER_ONLY: "RESERVATION_OWNER_ONLY",
  RESERVATION_WRONG_RESTAURANT: "RESERVATION_WRONG_RESTAURANT",

  // Reservation business rules
  RESERVATION_NOT_FOUND: "RESERVATION_NOT_FOUND",
  RESERVATION_SLOT_FULL: "RESERVATION_SLOT_FULL",
  RESERVATION_NOT_ACTIVE: "RESERVATION_NOT_ACTIVE",
  RESERVATION_TIME_INVALID: "RESERVATION_TIME_INVALID",
  RESERVATION_OWNER_NO_RESTAURANT: "RESERVATION_OWNER_NO_RESTAURANT",

  // Restaurant
  RESTAURANT_NOT_FOUND: "RESTAURANT_NOT_FOUND",

  // User / signup
  USER_EMAIL_EXISTS: "USER_EMAIL_EXISTS",
  USER_OWNER_RESTAURANT_REQUIRED: "USER_OWNER_RESTAURANT_REQUIRED",
  RESTAURANT_ALREADY_OWNED: "RESTAURANT_ALREADY_OWNED",

  // Prisma / infrastructure
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Validation (Zod)
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
